# Generated by Django 6.0.1 on 2026-01-29 17:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voters", "0002_election_candidate_voter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Voter",
            new_name="Vote",
        ),
    ]
