# Generated by Django 6.0.1 on 2026-01-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voters", "0003_rename_voter_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("voter", "Voter"),
                    ("candidate", "Candidate"),
                ],
                default="voter",
                max_length=20,
            ),
        ),
    ]
