# Generated by Django 6.0.1 on 2026-01-30 07:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voters", "0004_alter_profile_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="election",
            old_name="end_time",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="election",
            old_name="start_time",
            new_name="start_date",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="cast_at",
            new_name="voted_at",
        ),
        migrations.AddField(
            model_name="candidate",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="election",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="election",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_elections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
