# Generated by Django 6.0.1 on 2026-01-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voters", "0005_rename_end_time_election_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
