# Generated by Django 6.0.3 on 2026-04-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='voter_id',
            field=models.CharField(help_text='Enter your Citizenship No. / Student ID / Phone Number', max_length=30, null=True, unique=True),
        ),
    ]
