# Generated by Django 6.0.3 on 2026-04-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('voter', 'Voter'), ('organizer', 'Organizer')], default='voter', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='voter_id',
            field=models.CharField(help_text='Citizenship No. / Student ID / Phone Number', max_length=30, null=True, unique=True),
        ),
    ]
