# Generated by Django 6.0.3 on 2026-04-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_candidate_status_alter_candidate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='eligibility_type',
            field=models.CharField(choices=[('open', 'Open — Anyone registered can vote'), ('domain', 'Domain — Only specific email domain'), ('id_list', 'ID List — Only specific voter IDs')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='election',
            name='eligibility_value',
            field=models.TextField(blank=True, help_text='Domain: e.g. school.edu | ID List: e.g. ID001,ID002,ID003', null=True),
        ),
    ]
