# Generated by Django 5.2.14 on 2026-05-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
